# Generated by Django 4.1.7 on 2023-02-25 16:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('linkId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('linkDescription', models.CharField(max_length=200, verbose_name='链接描述')),
                ('linkUrl', models.CharField(max_length=200, verbose_name='链接地址')),
                ('linkRemark', models.CharField(max_length=200, verbose_name='链接备注')),
                ('userName', models.CharField(default='niki', max_length=50, verbose_name='账户')),
                ('passWord', models.CharField(default='123456', max_length=20, verbose_name='密码')),
            ],
        ),
    ]
