# Generated by Django 4.1.7 on 2023-02-20 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkDescription', models.CharField(max_length=200, verbose_name='链接描述')),
                ('linkUrl', models.CharField(max_length=200, verbose_name='链接地址')),
                ('linkRemark', models.CharField(max_length=200, verbose_name='链接备注')),
            ],
        ),
    ]
